package com.tataskan.pos.util

object Strings {
    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "TataskanPOS",
            "dashboard" to "Dashboard",
            "start_pos" to "Start POS",
            "inventory" to "Manage Inventory",
            "reports" to "Sales Reports",
            "settings" to "App Settings",
            "feedback" to "Give Feedback",
            "welcome_title" to "Welcome to TataskanPOS! 🏪",
            "welcome_msg" to "Let's set up your shop in 3 easy steps:",
            "welcome_step1" to "1️⃣ Add your store name and currency in Settings.",
            "welcome_step2" to "2️⃣ Create your first product in Inventory.",
            "welcome_step3" to "3️⃣ Go to 'Start POS' to make your first sale!",
            "got_it" to "Got it, Let's go!",
            "cart_empty" to "Your cart is empty",
            "scan_tip" to "Tip: Tap the scanner icon at the top to quickly add items using your phone's camera!",
            "inventory_empty" to "Your inventory is empty",
            "print_tip" to "Tip: Tap the printer icon below to print labels for your products.",
            "out_of_stock" to "OUT OF STOCK",
            "low_stock" to "Low Stock",
            "delete_confirm_title" to "WIPE ALL DATA?",
            "delete_confirm_msg" to "This will permanently delete your store profile, all products, all sales history, and your user account. This action is IRREVERSIBLE. Are you absolutely sure?",
            "yes_wipe" to "YES, WIPE DATA",
            "cancel" to "Cancel",
            "apply_restart" to "Apply Language & Restart",
            "pos_subtitle" to "Checkout & Billing",
            "quick_guide" to "Quick Guide",
            "guide_inventory" to "Manage products and stock levels.",
            "guide_pos" to "Ring up sales and handle payments.",
            "guide_barcode" to "Scan or enter barcodes for products.",
            "guide_labels" to "Print professional labels for your items.",
            "guide_backup" to "Export your data for safekeeping.",
            "grand_total" to "Grand Total",
            "checkout" to "Checkout",
            "amount_received" to "Amount Received",
            "change" to "Change",
            "complete_sale" to "Complete Sale",
            "confirm_sale" to "Confirm Sale",
            "total" to "Total",
            "received" to "Received",
            "confirm" to "Confirm",
            "basic_info" to "Basic Information",
            "product_name" to "Product Name",
            "username" to "Username",
            "password" to "Password",
            "category" to "Category",
            "pricing_stock" to "Pricing & Stock",
            "price" to "Selling Price",
            "cost" to "Unit Cost",
            "stock_level" to "Stock Level",
            "stock_label" to "Stock",
            "barcode" to "Barcode",
            "enter_barcode" to "Enter Barcode",
            "save_product" to "Save Product",
            "individual_downloads" to "Individual Downloads",
            "download_barcode" to "Download Barcode",
            "download_qr" to "Download QR Code",
            "delete_product" to "Delete Product",
            "delete_product_confirm" to "Are you sure you want to delete this product?",
            "app_experience" to "App Experience",
            "show_help" to "Show Quick Help",
            "show_help_desc" to "Display the onboarding guide on the dashboard.",
            "business_profile" to "Business Profile",
            "business_profile_tip" to "This information will appear on your receipts.",
            "store_name" to "Store Name",
            "store_address" to "Store Address",
            "phone_number" to "Phone Number",
            "receipts_tax" to "Receipts & Tax",
            "receipts_tax_tip" to "Configure tax rates and receipt footers.",
            "enable_receipts" to "Enable Receipts",
            "enable_receipts_desc" to "Generate digital receipts for sales.",
            "tax_percentage" to "Tax Percentage (%)",
            "receipt_footer" to "Receipt Footer Message",
            "label_defaults" to "Label Defaults",
            "label_defaults_tip" to "Default settings for product labels.",
            "show_name_label" to "Show Product Name",
            "show_name_label_desc" to "Include product name on labels.",
            "show_price_label" to "Show Price",
            "show_price_label_desc" to "Include price on labels.",
            "regional_display" to "Regional & Display",
            "regional_display_tip" to "Localize your app's language and currency.",
            "app_language" to "App Language",
            "select_language" to "Select Language",
            "restart_required" to "Restart Required",
            "restart_msg" to "The app needs to restart to apply the new language.",
            "restart_now" to "Restart Now",
            "currency" to "Currency",
            "currency_symbol" to "Currency Symbol",
            "maintenance_account" to "Maintenance & Account",
            "maintenance_tip" to "Export data or manage your account.",
            "restore_file" to "Restore from File",
            "already_have_backup" to "Already have a backup? Restore from File",
            "account_management" to "Account Management",
            "delete_shop" to "Delete Shop & Wipe Data",
            "export_success" to "Export successful!",
            "export_failed" to "Export failed.",
            "error" to "Error",
            "store_logo" to "Store Logo",
            "currency_placeholder" to "e.g. ₱, $, €",
            "bulk_scan_mode" to "Bulk Scan Mode",
            "bulk_mode_active" to "Bulk Mode Active",
            "start_guided_tutorial" to "Re-play Guided Tutorial",
            "tutorial_skip" to "Skip",
            "tutorial_next" to "Next",
            "tutorial_finish" to "Finish",
            "tut_welcome_title" to "Quick App Tour",
            "tut_welcome_desc" to "Welcome! Let's take a quick look at how TataskanPOS works.",
            "tut_finance_title" to "Track Your Money",
            "tut_finance_desc" to "See your sales and profit at a glance on the dashboard.",
            "tut_pos_title" to "Ready to Sell?",
            "tut_pos_desc" to "Tap the POS tab in the navigation bar to start a sale.",
            "tut_inventory_title" to "Manage Products",
            "tut_inventory_desc" to "This is where you add your items and set their prices.",
            "tut_reports_title" to "Analyze Your Business",
            "tut_reports_desc" to "View detailed charts and export professional PDF reports.",
            "tut_promos_title" to "Boost Your Sales",
            "tut_promos_desc" to "Create discount vouchers for your loyal customers.",
            "tut_pos_scan_title" to "Scan Products",
            "tut_pos_scan_desc" to "Tap the scanner icon to quickly add items using your phone's camera.",
            "tut_scanner_explain_title" to "How to Scan",
            "tut_scanner_explain_desc" to "Point your camera at barcodes to scan them. Tip: Use 'Bulk Mode' to scan multiple items quickly without leaving the camera screen. Note: You can only scan products that are already in your inventory.",
            "tut_checkout_btn_title" to "Ready to Pay?",
            "tut_checkout_btn_desc" to "Tap Checkout to proceed to the payment screen.",
            "tut_amount_received_title" to "Enter Payment",
            "tut_amount_received_desc" to "Type the amount you received from the customer here.",
            "tut_complete_sale_title" to "Finish Sale",
            "tut_complete_sale_desc" to "Tap this button to record the sale and generate a receipt.",
            "tut_finish_title" to "POS Tour Complete!",
            "tut_finish_desc" to "You've successfully scanned a product and completed a sale. Next, let's look at your inventory.",
            "tut_inventory_home_title" to "Manage Inventory",
            "tut_inventory_home_desc" to "Tap here to manage your products, stock levels, and pricing.",
            "tut_inv_search_title" to "Search Products",
            "tut_inv_search_desc" to "Quickly find items by name, category, or barcode.",
            "tut_inv_low_stock_title" to "Low Stock Filter",
            "tut_inv_low_stock_desc" to "Tap here to see items that are running low.",
            "tut_inv_filter_title" to "Category Filter",
            "tut_inv_filter_desc" to "Organize your view by choosing a specific product category.",
            "tut_inv_add_title" to "Add New Product",
            "tut_inv_add_desc" to "Tap the + button to create a new item. Go ahead and add one now!",
            "tut_inv_barcode_gen_title" to "Auto Barcode",
            "tut_inv_barcode_gen_desc" to "You can type your own barcode or tap this button to generate a unique one automatically.",
            "tut_inv_save_title" to "Save Product",
            "tut_inv_save_desc" to "Once you're done filling in the details, tap Save to add the item to your inventory.",
            "tut_inv_card_title" to "Product Overview",
            "tut_inv_card_desc" to "This card shows the price and current stock. Use + and - for fast adjustments, or tap the card for more details.",
            "tut_inv_detail_title" to "Product Details",
            "tut_inv_detail_desc" to "Here you can see all information for this product.",
            "tut_inv_download_title" to "Labels & Codes",
            "tut_inv_download_desc" to "Download the barcode or QR code for this specific product to your gallery.",
            "tut_inv_delete_title" to "Remove Product",
            "tut_inv_delete_desc" to "You can permanently delete this item if needed.",
            "tut_inv_print_title" to "Bulk Label Tool",
            "tut_inv_print_desc" to "Generate and save a PDF of labels for multiple products at once.",
            "tut_more_nav_title" to "More Tools",
            "tut_more_nav_desc" to "Discover additional features like Reports, Promos, and Settings here.",
            "tut_more_reports_title" to "Sales Reports",
            "tut_more_reports_desc" to "Track your business performance with detailed sales analytics.",
            "tut_more_promos_title" to "Promotions",
            "tut_more_promos_desc" to "Create discount codes to attract more customers.",
            "tut_more_labels_title" to "Label Generator",
            "tut_more_labels_desc" to "Print barcodes and QR codes for your products in bulk.",
            "tut_reporting_export_title" to "Export Reports",
            "tut_reporting_export_desc" to "Tap here to generate a professional PDF report of your sales to share or print.",
            "tut_promo_add_title" to "Create Promotions",
            "tut_promo_add_desc" to "Tap the + button to create a new discount voucher for your customers.",
            "tut_label_gen_title" to "Generate Labels",
            "tut_label_gen_desc" to "After selecting products, tap here to create a PDF sheet of barcodes or QR codes.",
            "tut_more_settings_title" to "App Settings",
            "tut_more_settings_desc" to "Configure your shop profile, tax, language, and backups.",
            "tut_more_feedback_title" to "Send Feedback",
            "tut_more_feedback_desc" to "Share your suggestions or report issues to help us improve.",
            "tut_settings_business_title" to "Business Profile",
            "tut_settings_business_desc" to "Set your store name, address, and logo for your receipts.",
            "tut_settings_tax_title" to "Receipts & Tax",
            "tut_settings_tax_desc" to "Manage tax percentages and receipt footer messages.",
            "tut_settings_regional_title" to "Regional Settings",
            "tut_settings_regional_desc" to "Change the app language and your local currency symbol.",
            "tut_settings_backup_title" to "Data Safety",
            "tut_settings_backup_desc" to "Create local backups or restore data from an external file.",
            "tut_settings_demo_title" to "Test with Demo Data",
            "tut_settings_demo_desc" to "Load pre-made products and sales to quickly test all the features of the app. Note: This will overwrite your current inventory and settings.",
            "tut_feedback_stars_title" to "Rate Us",
            "tut_feedback_stars_desc" to "Give us a star rating based on your experience.",
            "tut_feedback_submit_title" to "Submit Suggestions",
            "tut_feedback_submit_desc" to "Type your feedback and tap submit to send it to our team.",
            "tut_final_title" to "Tutorial Complete!",
            "tut_final_desc" to "You're all set! You've learned how to sell products and manage your inventory. Happy selling!",
            "tut_back_tip_title" to "Great Job!",
            "tut_back_tip_desc" to "You've explored this feature. Tap the 'Back' arrow at the top left to continue the tour.",
            "added_to_cart" to "Added to cart",
            "product_not_found" to "Product not found",
            "camera_permission_required" to "Camera permission required",
            "grant_permission" to "Grant Permission",
            "sales_reports" to "Sales Reports",
            "overview" to "Overview",
            "today" to "Today",
            "this_month" to "This Month",
            "recent_transactions" to "Recent Transactions",
            "export_pdf" to "Export PDF",
            "share_report" to "Share Report",
            "transactions_count" to "Transactions",
            "items_count" to "Items",
            "receipt" to "Receipt",
            "done" to "Done",
            "save_pdf" to "Save PDF",
            "share" to "Share",
            "receipt_no" to "Receipt No.",
            "cash_received" to "Cash Received",
            "change_label" to "Change",
            "reporting_tip" to "This screen shows your business performance. Tap the download icon at the top to export a professional PDF report.",
            "label_generator_tool" to "Label Generator Tool",
            "generate_pdf" to "Generate PDF",
            "total_labels" to "Total Labels",
            "code_type" to "Code Type",
            "select_size" to "Select Size",
            "qty_per_product" to "Qty per Product",
            "filter_products" to "Filter products...",
            "no_products_found" to "No products found",
            "no_matching_products" to "No matching products",
            "preview" to "Preview",
            "not_available" to "N/A",
            "saved_to_gallery" to "Saved to Gallery",
            "save_changes" to "Save Changes",
            "settings_saved" to "Settings saved!",
            "security" to "Security",
            "change_password" to "Change Password",
            "new_password" to "New Password",
            "update_password" to "Update Password",
            "password_updated" to "Password updated successfully!",
            "password_update_failed" to "Failed to update password.",
            "account_already_exists" to "Account Already Exists",
            "one_account_limit" to "Only one account is allowed per phone.",
            "invalid_shop_name" to "Shop name must be at least 3 characters.",
            "invalid_username" to "Username must be at least 3 characters.",
            "invalid_password" to "Password must be at least 4 characters.",
            "confirm_password" to "Confirm Password",
            "passwords_dont_match" to "Passwords do not match",
            "go_to_login" to "Go to Login",
            "already_have_account" to "Need to Restore?",
            "dont_have_account" to "Don't have an account? Register",
            "welcome_back" to "Welcome Back",
            "login_subtitle" to "Login to your TataskanPOS account",
            "invalid_login" to "Invalid username or password",
            "login" to "Login",
            "register" to "Register",
            "legal_privacy" to "Legal & Privacy",
            "view_privacy" to "View Privacy Policy",
            "view_tos" to "View Terms of Service",
            "legal_notice" to "Notice: TataskanPOS is an offline-first app. Your business data is stored locally.",
            "close" to "Close",
            "backup_warning" to "IMPORTANT: Always download your backups to a safe location (like Google Drive or another device). Local backups will be lost if you clear app data, uninstall, or if the phone is lost.",
            "download" to "Download",
            "delete" to "Delete",
            "generate_backup" to "Generate New Backup",
            "load_demo_title" to "Load Demo Data?",
            "load_demo_msg" to "Warning: This will overwrite your current inventory and settings with sample data. Please create a backup first if you want to keep your current data. Do you want to proceed?",
            "local_backups" to "Local Backup Files",
            "logout" to "Logout",
            "copyright" to "© 2026 TataskanPOS.",
            "product_details" to "Product Details",
            "add_product" to "Add Product",
            "edit_product" to "Edit Product",
            "shopping_cart" to "Shopping Cart",
            "checkout" to "Checkout",
            "scan_barcode" to "Scan Barcode",
            "search_products" to "Search Products",
            "bulk_labels" to "Bulk Label Generator",
            "promos" to "Promo Discounts",
            "add_promo" to "Add Promo",
            "no_promos" to "No promos found",
            "promo_applied" to "Promo Applied",
            "promo_invalid" to "Invalid Promo Code",
            "discount" to "Discount",
            "stock_adjustments" to "Stock Adjustments",
            "reason" to "Reason",
            "adjustment_success" to "Stock adjusted successfully",
            "sold" to "Sold",
            "restocked" to "Restocked",
            "damaged" to "Damaged",
            "expired" to "Expired",
            "lost" to "Lost",
            "manual" to "Manual",
            "desc_prod_name" to "Enter the full name of the product.",
            "desc_prod_category" to "Choose a category to organize your inventory.",
            "desc_prod_price" to "The price customers will pay.",
            "desc_prod_cost" to "What you paid for this item.",
            "desc_prod_stock" to "How many items you have available.",
            "desc_prod_barcode" to "Enter own code or tap refresh to auto-generate.",
            "backup_pin" to "4-Digit Backup PIN",
            "enter_backup_pin" to "4-Digit Backup PIN",
            "invalid_backup_pin" to "Backup PIN must be exactly 4 digits.",
            "forgot_password" to "Forgot Password / Reset PIN",
            "reset_with_pin" to "Reset via Backup PIN",
            "reset_via_facebook" to "Request Ticket via Facebook",
            "ticket_number" to "Your Ticket Code:",
            "enter_admin_code" to "Admin Verification Code",
            "verify_and_reset" to "Verify & Reset Credentials",
            "new_password" to "New Password",
            "new_backup_pin" to "New 4-Digit PIN",
            "promo_code" to "Trial Extension Promo Code",
            "enter_promo_code" to "Enter Secret Promo Code",
            "redeem_code" to "Redeem Promo Code",
            "code_redeemed_success" to "Trial extension promo code successfully redeemed!",
            "code_already_used" to "This promo code has already been used on this device.",
            "invalid_promo_code" to "Invalid promo code or verification code.",
            "expired_ticket" to "Ticket has expired (5-minute limit). Please request a new ticket.",
            "payment_method" to "Payment Method",
            "payment_cash" to "Cash",
            "payment_digital" to "Digital (GCash / Maya)",
            "digital_payment_qr" to "Merchant Digital Payment QR",
            "scan_qr_to_pay" to "Scan QR code to pay exact total of",
            "show_merchant_qr" to "Show Merchant Payment QR",
            "digital_payment_qrs" to "Digital Payment QR Codes",
            "digital_payment_qrs_desc" to "Upload your GCash or Maya store QR codes for customer checkout.",
            "upload_gcash_qr" to "Upload GCash QR Code",
            "upload_maya_qr" to "Upload Maya QR Code",
            "google_drive_backup" to "Google Drive Cloud Backup",
            "google_drive_desc" to "Link your Google account to enable automatic nightly backups to your personal Google Drive.",
            "link_google_drive" to "Link Google Account",
            "unlink_google_drive" to "Unlink Account",
            "sync_now_drive" to "Sync Now to Google Drive",
            "linked_as" to "Linked as:",
            "not_linked" to "Not Linked",
            "last_cloud_sync" to "Last Cloud Sync:",
            "never" to "Never",
            "load_demo_data" to "Load Demo Data",
            "reset_data_title" to "Reset Store Data",
            "reset_data_desc" to "Warning: This will permanently delete all products, categories, sales history, promos, and QR codes. Your user account will remain intact, and the guided tutorial will restart. Do you want to proceed?",
            "reset_now" to "Reset Data Now",
            "data_reset_success" to "Store data reset successfully!",
            "reset_success_title" to "Password Reset Successful!",
            "reset_success_desc" to "Your password and security PIN have been updated successfully. You can now log in with your new credentials.",
            "ok_login" to "OK, Login Now",
            "trial_extended_title" to "Trial Extension Successful!",
            "trial_extended_desc" to "Your TataskanPOS trial has been extended successfully! Tap Continue to resume using the app.",
            "continue_dashboard" to "Continue to Dashboard",
            "select_all" to "Select All",
            "deselect_all" to "Deselect All",
            "label_preview" to "Label Preview",
            "barcode_code" to "Barcode",
            "qr_code" to "QR Code"
        ),
        "tl" to mapOf(
            "app_name" to "TataskanPOS",
            "dashboard" to "Dashboard",
            "start_pos" to "Simulan ang POS",
            "inventory" to "Pamahalaan ang Imbentaryo",
            "reports" to "Ulat ng Benta",
            "settings" to "Settings ng App",
            "feedback" to "Magbigay ng Feedback",
            "welcome_title" to "Maligayang pagdating sa TataskanPOS! 🏪",
            "welcome_msg" to "I-set up natin ang iyong tindahan sa 3 madaling hakbang:",
            "welcome_step1" to "1️⃣ Idagdag ang pangalan ng tindahan at pera sa Settings.",
            "welcome_step2" to "2️⃣ Gumawa ng iyong unang produkto sa Inventory.",
            "welcome_step3" to "3️⃣ Pumunta sa 'Start POS' para sa iyong unang benta!",
            "got_it" to "Nakuha ko na, Tara!",
            "cart_empty" to "Walang laman ang iyong cart",
            "scan_tip" to "Tip: I-tap ang icon ng scanner sa itaas para mabilis na makapagdagdag gamit ang camera!",
            "inventory_empty" to "Walang laman ang iyong imbentaryo",
            "print_tip" to "Tip: I-tap ang icon ng printer sa ibaba para mag-print ng mga label.",
            "out_of_stock" to "UBOS NA ANG STOCK",
            "low_stock" to "Mababa ang Stock",
            "delete_confirm_title" to "BURAHIN LAHAT NG DATA?",
            "delete_confirm_msg" to "Permanenteng mabubura ang profile ng tindahan, lahat ng produkto, kasaysayan ng benta, at ang iyong account. Hindi na ito mababawi. Sigurado ka ba?",
            "yes_wipe" to "OO, BURAHIN LAHAT",
            "cancel" to "Kanselahin",
            "apply_restart" to "Ilapat ang Wika at Mag-restart",
            "pos_subtitle" to "Checkout at Pagbabayad",
            "quick_guide" to "Mabilis na Gabay",
            "guide_inventory" to "Pamahalaan ang mga produkto at stock.",
            "guide_pos" to "Itala ang mga benta at bayad.",
            "guide_barcode" to "I-scan o ilagay ang barcode.",
            "guide_labels" to "Mag-print ng mga label para sa item.",
            "guide_backup" to "I-export ang iyong data para sa kaligtasan.",
            "grand_total" to "Kabuuang Halaga",
            "checkout" to "Checkout",
            "amount_received" to "Halagang Natanggap",
            "change" to "Sukli",
            "complete_sale" to "Tapusin ang Benta",
            "confirm_sale" to "Kumpirmahin ang Benta",
            "total" to "Kabuuan",
            "received" to "Natanggap",
            "confirm" to "Kumpirmahin",
            "basic_info" to "Pangunahing Impormasyon",
            "product_name" to "Pangalan ng Produkto",
            "username" to "Username",
            "password" to "Password",
            "category" to "Kategorya",
            "pricing_stock" to "Presyo at Stock",
            "price" to "Presyong Paninda",
            "cost" to "Puhunan",
            "stock_level" to "Dami ng Stock",
            "stock_label" to "Stock",
            "barcode" to "Barcode",
            "enter_barcode" to "Ilagay ang Barcode",
            "save_product" to "I-save ang Produkto",
            "individual_downloads" to "Mga Download",
            "download_barcode" to "I-download ang Barcode",
            "download_qr" to "I-download ang QR Code",
            "delete_product" to "Burahin ang Produkto",
            "delete_product_confirm" to "Sigurado ka bang burahin ang produktong ito?",
            "app_experience" to "Karanasan sa App",
            "show_help" to "Ipakita ang Gabay",
            "show_help_desc" to "Ipakita ang gabay sa dashboard.",
            "business_profile" to "Profile ng Negosyo",
            "business_profile_tip" to "Lalabas ang impormasyong ito sa iyong mga resibo.",
            "store_name" to "Pangalan ng Tindahan",
            "store_address" to "Address ng Tindahan",
            "phone_number" to "Numero ng Telepono",
            "receipts_tax" to "Resibo at Buwis",
            "receipts_tax_tip" to "I-configure ang buwis at footer ng resibo.",
            "enable_receipts" to "Paganahin ang Resibo",
            "enable_receipts_desc" to "Gumawa ng digital na resibo.",
            "tax_percentage" to "Porsyento ng Buwis (%)",
            "receipt_footer" to "Mensahe sa Footer ng Resibo",
            "label_defaults" to "Default ng Label",
            "label_defaults_tip" to "Mga default na setting para sa label.",
            "show_name_label" to "Ipakita ang Pangalan",
            "show_name_label_desc" to "Isama ang pangalan sa label.",
            "show_price_label" to "Ipakita ang Presyo",
            "show_price_label_desc" to "Isama ang presyo sa label.",
            "regional_display" to "Rehiyon at Display",
            "regional_display_tip" to "I-set ang wika at pera.",
            "app_language" to "Wika ng App",
            "select_language" to "Pumili ng Wika",
            "restart_required" to "Kailangan ng Restart",
            "restart_msg" to "Kailangang i-restart ang app para mailapat ang wika.",
            "restart_now" to "I-restart Ngayon",
            "currency" to "Pera",
            "currency_symbol" to "Simbolo ng Pera",
            "maintenance_account" to "Maintenance at Account",
            "maintenance_tip" to "I-export ang data o pamahalaan ang account.",
            "restore_file" to "I-restore mula sa File",
            "already_have_backup" to "May backup na ba? I-restore mula sa File",
            "account_management" to "Pamamahala ng Account",
            "delete_shop" to "Burahin ang Tindahan at Data",
            "export_success" to "Tagumpay ang pag-export!",
            "export_failed" to "Bigo ang pag-export.",
            "error" to "Mali",
            "store_logo" to "Logo ng Tindahan",
            "currency_placeholder" to "hal. ₱, $, €",
            "bulk_scan_mode" to "Bulk Scan Mode",
            "bulk_mode_active" to "Naka-activate ang Bulk Mode",
            "start_guided_tutorial" to "Ulitin ang Guided Tutorial",
            "tutorial_skip" to "Laktawan",
            "tutorial_next" to "Susunod",
            "tutorial_finish" to "Tapos na",
            "tut_welcome_title" to "Tour ng App",
            "tut_welcome_desc" to "Maligayang pagdating! Hayaan mong ipakita namin kung paano gamitin ang TataskanPOS.",
            "tut_finance_title" to "Subaybayan ang Pera",
            "tut_finance_desc" to "Tingnan ang iyong benta at kita sa isang tingin.",
            "tut_pos_title" to "Handa ka na bang magbenta?",
            "tut_pos_desc" to "I-tap ang POS tab sa baba para simulan ang benta.",
            "tut_pos_scan_title" to "I-scan ang Produkto",
            "tut_pos_scan_desc" to "I-tap ang icon ng scanner para mabilis na makapagdagdag gamit ang camera.",
            "tut_scanner_explain_title" to "Paano mag-scan",
            "tut_scanner_explain_desc" to "Itutok ang camera sa barcode para ma-scan ito. Tip: Gamitin ang 'Bulk Mode' para mabilis na maka-scan ng maraming item nang hindi lumalabas sa camera. Paunawa: Maari mo lamang i-scan ang mga produktong nasa iyong inventory.",
            "tut_inventory_desc" to "Dito mo ilalagay ang iyong mga paninda at presyo.",
            "tut_reports_title" to "Suriin ang Negosyo",
            "tut_reports_desc" to "Tingnan ang mga chart at mag-export ng PDF reports.",
            "tut_promos_title" to "Palakasin ang Benta",
            "tut_promos_desc" to "Gumawa ng mga discount vouchers para sa mga suki.",
            "tut_finish_title" to "Tapos na ang POS Tour!",
            "tut_finish_desc" to "Matagumpay mong na-scan ang produkto at nakabuo ng benta. Susunod, tingnan natin ang iyong inventory.",
            "tut_inventory_home_title" to "Pamahalaan ang Imbentaryo",
            "tut_inventory_home_desc" to "I-tap ito para pamahalaan ang iyong mga produkto, stock, at presyo.",
            "tut_inv_search_title" to "Maghanap ng Produkto",
            "tut_inv_search_desc" to "Mabilis na hanapin ang mga item gamit ang pangalan, kategorya, o barcode.",
            "tut_inv_low_stock_title" to "Low Stock Filter",
            "tut_inv_low_stock_desc" to "I-tap dito para makita ang mga item na malapit nang maubos.",
            "tut_inv_filter_title" to "Category Filter",
            "tut_inv_filter_desc" to "I-organisa ang iyong view sa pamamagitan ng pagpili ng kategorya.",
            "tut_inv_add_title" to "Magdagdag ng Produkto",
            "tut_inv_add_desc" to "I-tap ang + button para gumawa ng bagong item. Subukan mong magdagdag ngayon!",
            "tut_inv_barcode_gen_title" to "Auto Barcode",
            "tut_inv_barcode_gen_desc" to "Maaari kang mag-type ng sariling barcode o i-tap ang button na ito para gumawa ng bago nang awtomatiko.",
            "tut_inv_save_title" to "I-save ang Produkto",
            "tut_inv_save_desc" to "Kapag tapos ka na sa mga detalye, i-tap ang Save para maidagdag ang item sa iyong imbentaryo.",
            "tut_inv_card_title" to "Product Overview",
            "tut_inv_card_desc" to "Makikita rito ang presyo at stock. Gamitin ang + at - para sa mabilis na adjustment.",
            "tut_inv_detail_title" to "Detalye ng Produkto",
            "tut_inv_detail_desc" to "Dito mo makikita ang lahat ng impormasyon para sa produktong ito.",
            "tut_inv_download_title" to "Labels at Codes",
            "tut_inv_download_desc" to "I-download ang barcode o QR code ng produktong ito sa iyong gallery.",
            "tut_inv_delete_title" to "Burahin ang Produkto",
            "tut_inv_delete_desc" to "Maari mong burahin ang item na ito kung kinakailangan.",
            "tut_inv_print_title" to "Bulk Label Tool",
            "tut_inv_print_desc" to "Gumawa ng PDF ng mga labels para sa maraming produkto nang sabay-sabay.",
            "tut_more_nav_title" to "Higit Pang Tools",
            "tut_more_nav_desc" to "Tuklasin ang iba pang feature gaya ng Reports, Promos, at Settings dito.",
            "tut_more_reports_title" to "Mga Ulat ng Benta",
            "tut_more_reports_desc" to "Subaybayan ang performance ng negosyo gamit ang sales analytics.",
            "tut_more_promos_title" to "Mga Promosyon",
            "tut_more_promos_desc" to "Gumawa ng discount codes para makaakit ng mga suki.",
            "tut_more_labels_title" to "Label Generator",
            "tut_more_labels_desc" to "Mag-print ng barcode at QR code para sa iyong mga produkto.",
            "tut_reporting_export_title" to "I-export ang Ulat",
            "tut_reporting_export_desc" to "I-tap dito para gumawa ng PDF report ng iyong mga benta na maaari mong i-share o i-print.",
            "tut_promo_add_title" to "Gumawa ng Promosyon",
            "tut_promo_add_desc" to "I-tap ang + button para gumawa ng bagong discount voucher para sa iyong mga customer.",
            "tut_label_gen_title" to "Gumawa ng mga Label",
            "tut_label_gen_desc" to "Pagkatapos pumili ng mga produkto, i-tap dito para gumawa ng PDF sheet ng mga barcode o QR codes.",
            "tut_more_settings_title" to "Settings ng App",
            "tut_more_settings_desc" to "I-configure ang iyong shop profile, buwis, wika, at backups.",
            "tut_more_feedback_title" to "Magbigay ng Feedback",
            "tut_more_feedback_desc" to "Ibahagi ang iyong mga mungkahi para matulungan kaming mapabuti ang app.",
            "tut_settings_business_title" to "Business Profile",
            "tut_settings_business_desc" to "I-set ang pangalan ng tindahan, address, at logo para sa resibo.",
            "tut_settings_tax_title" to "Resibo at Buwis",
            "tut_settings_tax_desc" to "Pamahalaan ang porsyento ng buwis at mensahe sa resibo.",
            "tut_settings_regional_title" to "Regional Settings",
            "tut_settings_regional_desc" to "Palitan ang wika ng app at simbolo ng pera.",
            "tut_settings_backup_title" to "Kaligtasan ng Data",
            "tut_settings_backup_desc" to "Gumawa ng lokal na backups o i-restore ang data mula sa file.",
            "tut_settings_demo_title" to "Subukan gamit ang Demo Data",
            "tut_settings_demo_desc" to "Mag-load ng mga sample na produkto at benta para mabilis na masubukan ang app. Paunawa: Mabubura ang iyong kasalukuyang inventory at settings nito.",
            "tut_feedback_stars_title" to "I-rate Kami",
            "tut_feedback_stars_desc" to "Magbigay ng star rating batay sa iyong karanasan.",
            "tut_feedback_submit_title" to "I-submit ang Mungkahi",
            "tut_feedback_submit_desc" to "I-type ang iyong feedback at i-tap ang submit.",
            "tut_final_title" to "Tapos na ang Tutorial!",
            "tut_final_desc" to "Handa ka na! Natutunan mo na kung paano magbenta at mamahala ng inventory. Good luck sa iyong negosyo!",
            "tut_back_tip_title" to "Magaling!",
            "tut_back_tip_desc" to "Nagawad mo na ang feature na ito. I-tap ang 'Back' arrow sa itaas para ipagpatuloy ang tour.",
            "added_to_cart" to "Naidagdag sa cart",
            "product_not_found" to "Hindi nahanap ang produkto",
            "camera_permission_required" to "Kailangan ng pahintulot sa camera",
            "grant_permission" to "Ibigay ang Pahintulot",
            "sales_reports" to "Ulat ng Benta",
            "overview" to "Pangkalahatang-ideya",
            "today" to "Ngayon",
            "this_month" to "Ngayong Buwan",
            "recent_transactions" to "Kamakailang Transaksyon",
            "export_pdf" to "I-export ang PDF",
            "share_report" to "Ibahagi ang Ulat",
            "transactions_count" to "Mga Transaksyon",
            "items_count" to "Mga Item",
            "receipt" to "Resibo",
            "done" to "Tapos na",
            "save_pdf" to "I-save ang PDF",
            "share" to "Ibahagi",
            "receipt_no" to "Numero ng Resibo",
            "cash_received" to "Natanggap na Pera",
            "change_label" to "Sukli",
            "reporting_tip" to "Ipinapakita ng screen na ito ang performance ng iyong negosyo. I-tap ang download icon sa itaas para mag-export ng professional na PDF report.",
            "label_generator_tool" to "Tool para sa Paggawa ng Label",
            "generate_pdf" to "Gumawa ng PDF",
            "total_labels" to "Total Labels",
            "code_type" to "Uri ng Code",
            "select_size" to "Pumili ng Laki",
            "qty_per_product" to "Dami bawat Produkto",
            "filter_products" to "Mag-filter ng mga produkto...",
            "no_products_found" to "Walang nahanap na produkto",
            "no_matching_products" to "Walang tumutugmang produkto",
            "preview" to "Preview",
            "not_available" to "Walang impormasyon",
            "saved_to_gallery" to "Na-save sa Gallery",
            "save_changes" to "I-save ang mga Pagbabago",
            "settings_saved" to "Na-save na ang settings!",
            "security" to "Seguridad",
            "change_password" to "Palitan ang Password",
            "new_password" to "Bagong Password",
            "update_password" to "I-update ang Password",
            "password_updated" to "Matagumpay na na-update ang password!",
            "password_update_failed" to "Bigo sa pag-update ng password.",
            "account_already_exists" to "Mayroon nang Account",
            "one_account_limit" to "Isang account lamang ang pinapayagan bawat telepono.",
            "invalid_shop_name" to "Ang pangalan ng shop ay dapat hindi bababa sa 3 characters.",
            "invalid_username" to "Ang username ay dapat hindi bababa sa 3 characters.",
            "invalid_password" to "Ang password ay dapat hindi bababa sa 4 na characters.",
            "confirm_password" to "Kumpirmahin ang Password",
            "passwords_dont_match" to "Hindi magkatugma ang password",
            "go_to_login" to "Pumunta sa Login",
            "already_have_account" to "Kailangang i-Restore?",
            "dont_have_account" to "Wala pang account? Mag-register",
            "welcome_back" to "Maligayang Pagbabalik",
            "login_subtitle" to "Mag-login sa iyong TataskanPOS account",
            "invalid_login" to "Maling username o password",
            "login" to "Login",
            "register" to "Mag-register",
            "legal_privacy" to "Legal at Privacy",
            "view_privacy" to "Tingnan ang Privacy Policy",
            "view_tos" to "Tingnan ang Terms of Service",
            "legal_notice" to "Paunawa: Ang TataskanPOS ay isang offline-first na app. Ang iyong business data ay naka-store nang lokal.",
            "close" to "Isara",
            "backup_warning" to "MAHALAGA: Palaging i-download ang iyong mga backup sa isang ligtas na lokasyon (tulad ng Google Drive o ibang device). Mawawala ang mga lokal na backup kung i-clear mo ang data ng app, i-uninstall, o kung mawala ang telepono.",
            "download" to "I-download",
            "delete" to "Burahin",
            "generate_backup" to "Gumawa ng Bagong Backup",
            "load_demo_title" to "Mag-load ng Demo Data?",
            "load_demo_msg" to "Babala: Buburahin nito ang iyong kasalukuyang imbentaryo at settings para palitan ng sample data. Mangyaring gumawa muna ng backup kung nais mong itago ang iyong data. Nais mo bang magpatuloy?",
            "local_backups" to "Mga Lokal na Backup File",
            "logout" to "Mag-logout",
            "copyright" to "© 2026 TataskanPOS.",
            "product_details" to "Detalye ng Produkto",
            "add_product" to "Magdagdag ng Produkto",
            "edit_product" to "I-edit ang Produkto",
            "shopping_cart" to "Shopping Cart",
            "checkout" to "Checkout",
            "scan_barcode" to "I-scan ang Barcode",
            "search_products" to "Maghanap ng Produkto",
            "bulk_labels" to "Bulk Label Generator",
            "promos" to "Mga Promo Discount",
            "add_promo" to "Magdagdag ng Promo",
            "no_promos" to "Walang nahanap na promo",
            "promo_applied" to "Applied na ang Promo",
            "promo_invalid" to "Maling Promo Code",
            "discount" to "Discount",
            "stock_adjustments" to "Stock Adjustments",
            "reason" to "Dahilan",
            "adjustment_success" to "Maayos na na-adjust ang stock",
            "sold" to "Nabenta",
            "restocked" to "Nag-restock",
            "damaged" to "Sira",
            "expired" to "Expired",
            "lost" to "Nawala",
            "manual" to "Manual",
            "desc_prod_name" to "Ilagay ang buong pangalan ng produkto.",
            "desc_prod_category" to "Pumili ng kategorya para sa iyong imbentaryo.",
            "desc_prod_price" to "Presyo na babayaran ng customer.",
            "desc_prod_cost" to "Puhunan sa item na ito.",
            "desc_prod_stock" to "Dami ng item na mayroon ka.",
            "desc_prod_barcode" to "Ilagay ang code o i-tap ang refresh para sa auto-generate.",
            "backup_pin" to "4-Digit Backup PIN",
            "enter_backup_pin" to "4-Digit Backup PIN",
            "invalid_backup_pin" to "Ang Backup PIN ay dapat eksaktong 4 na numero.",
            "forgot_password" to "Nakalimutan ang Password / I-reset ang PIN",
            "reset_with_pin" to "I-reset gamit ang Backup PIN",
            "reset_via_facebook" to "Humingi ng Ticket sa Facebook",
            "ticket_number" to "Ang Iyong Ticket Code:",
            "enter_admin_code" to "Admin Verification Code",
            "verify_and_reset" to "I-verify at I-reset",
            "new_password" to "Bagong Password",
            "new_backup_pin" to "Bagong 4-Digit PIN",
            "promo_code" to "Trial Extension Promo Code",
            "enter_promo_code" to "I-enter ang Secret Promo Code",
            "redeem_code" to "I-redeem ang Promo Code",
            "code_redeemed_success" to "Matagumpay na na-redeem ang promo code!",
            "code_already_used" to "Ang promo code na ito ay nagamit na sa teleponong ito.",
            "invalid_promo_code" to "Maling promo code o verification code.",
            "expired_ticket" to "Nag-expire na ang ticket (5 minutong limitasyon). Humingi ng bagong ticket.",
            "payment_method" to "Paraan ng Pagbabayad",
            "payment_cash" to "Cash",
            "payment_digital" to "Digital (GCash / Maya)",
            "digital_payment_qr" to "Merchant Digital Payment QR",
            "scan_qr_to_pay" to "I-scan ang QR code para magbayad ng exact total na",
            "show_merchant_qr" to "Ipakita ang Merchant Payment QR",
            "digital_payment_qrs" to "Mga QR Code para sa Digital Payment",
            "digital_payment_qrs_desc" to "I-upload ang iyong GCash o Maya QR codes para sa customer checkout.",
            "upload_gcash_qr" to "I-upload ang GCash QR Code",
            "upload_maya_qr" to "I-upload ang Maya QR Code",
            "google_drive_backup" to "Google Drive Cloud Backup",
            "google_drive_desc" to "I-link ang iyong Google account para sa awtomatiko at ligtas na backup sa iyong Google Drive.",
            "link_google_drive" to "I-link ang Google Account",
            "unlink_google_drive" to "I-unlink ang Account",
            "sync_now_drive" to "I-sync Ngayon sa Google Drive",
            "linked_as" to "Naka-link bilang:",
            "not_linked" to "Hindi Naka-link",
            "last_cloud_sync" to "Huling Cloud Sync:",
            "never" to "Hindi Pa",
            "load_demo_data" to "Mag-load ng Demo Data",
            "reset_data_title" to "I-reset ang Data",
            "reset_data_desc" to "Babala: Permanenteng mabubura ang lahat ng produkto, kategorya, sales history, promos, at QR codes. Mananatili ang iyong account, at uulitin ang guided tutorial. Nais mo bang magpatuloy?",
            "reset_now" to "I-reset Ngayon",
            "data_reset_success" to "Matagumpay na na-reset ang data!",
            "reset_success_title" to "Tagumpay ang Pag-reset ng Password!",
            "reset_success_desc" to "Matagumpay na na-update ang iyong password at security PIN. Maaari ka nang mag-login gamit ang iyong bagong impormasyon.",
            "ok_login" to "OK, Mag-login Na",
            "trial_extended_title" to "Tagumpay ang Pagpapalawig ng Trial!",
            "trial_extended_desc" to "Matagumpay na naipalawig ang iyong TataskanPOS trial! I-tap ang Magpatuloy para magamit ulit ang app.",
            "continue_dashboard" to "Magpatuloy sa Dashboard",
            "select_all" to "Piliin Lahat",
            "deselect_all" to "Alisin ang Lahat",
            "label_preview" to "Preview ng Label",
            "barcode_code" to "Barcode",
            "qr_code" to "QR Code"
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
